sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "12.8.0"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - npm install -g --silent @angular/cli

install:
  - npm install

script:
  - ng build --configuration=heroku

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  skip_cleanup: false
  app: qcm-angular-frontend
  on:
    repo: EricMuller/qcm-angular-frontend
